<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Item;

class ItemSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $items = array (
            ['code' => "BG1051", 'description' => "Red Offals = Cow", 'category' => "cm-offals"],
            ['code' => "BG1054", 'description' => "Hide/Skin, Cow", 'category' => "cm-offals"],
            ['code' => "BG1056", 'description' => "Blood, Cow", 'category' => "cm-offals"],
            ['code' => "BG1057", 'description' => "Tripe fat", 'category' => "cm-offals"],
            ['code' => "BG1058", 'description' => "Carcass Tripe Trimmings", 'category' => "cm-offals"],
            ['code' => "BG1059", 'description' => "Ox Head (per piece)", 'category' => "cm-offals"],
            ['code' => "BG1060", 'description' => "Hooves (4 pieces), Cow", 'category' => "cm-offals"],
            ['code' => "BG1062", 'description' => "Green Offals (ONLY)", 'category' => "cm-offals"],
            ['code' => "BG1063", 'description' => "Ox Heart", 'category' => "cm-offals"],
            ['code' => "BG1064", 'description' => "Head Musks (Skins)", 'category' => "cm-offals"],
            ['code' => "BG1065", 'description' => "Cow Bile Juice", 'category' => "cm-offals"],
            ['code' => "BG1066", 'description' => "Beef Omasum", 'category' => "cm-offals"],
            ['code' => "BG1068", 'description' => "Beef Cardio =(Tripe Trimmings)", 'category' => "cm-offals"],
            ['code' => "BG1254", 'description' => "Beef Bull Testicles", 'category' => "cm-offals"],
            ['code' => "BG1321", 'description' => "Blood Plasma", 'category' => "cm-offals"],
            ['code' => "BG1482", 'description' => "Ox=Liver", 'category' => "cm-offals"],
            ['code' => "BJ31100265", 'description' => "Ox Horn (per unit)", 'category' => "cm-offals"],
            ['code' => "BJ31100316", 'description' => "Beef Omasum Trimmings /Kg", 'category' => "cm-offals"],
            ['code' => "BG1000", 'description' => "High Grade-Cattle- Species", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1001", 'description' => "Comm. Grade-Cattle- Species", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1002", 'description' => "CMFAQ Grade-Cattle- Species", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1004", 'description' => "CMSTD Grade-Cattle- Species", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1005", 'description' => "High Grade-Steer- Livestock", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1006", 'description' => "High Grade-Steer- Livestock", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1007", 'description' => "High Grade-Heifer- Livestock", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1008", 'description' => "High Grade-Bull- Livestock", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1009", 'description' => "High Grade-Cow- Livestock", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1011", 'description' => "Comm Grade - Steer Livestock", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1012", 'description' => "Comm Grade - Heifer Livestock", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1013", 'description' => "Comm Grade - Bull Livestock", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1014", 'description' => "Comm Grade - Cow Livestock", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1016", 'description' => "CMFAQ - Livestock", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1018", 'description' => "CMSTD - Livestock", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1021", 'description' => "Steer - High Grade Carcass", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1022", 'description' => "Heifer - High Grade Carcass", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1023", 'description' => "Bull - High Grade Carcass", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1024", 'description' => "Cow - High Grade Carcass", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1025", 'description' => "HG Carcass without Kidney", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1031", 'description' => "Steer - Comm. Grade Carcass", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1032", 'description' => "Heifer - Comm. Grade Carcass", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1033", 'description' => "Bull - Comm. Grade Carcass", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1034", 'description' => "Cow - Comm. Grade Carcass", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1036", 'description' => "CMFAQ Grade Carcass", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1037", 'description' => "CMSTD Grade Carcass", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1038", 'description' => "CMFAQ-Com Grade Carcass", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1045", 'description' => "Goat Carcass + Slgtr & Vet Fee", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1071", 'description' => "High Grade - Fore-Quarters", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1072", 'description' => "High Grade - Hind-Quarters", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1073", 'description' => "High Grade Beef - Sides", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1081", 'description' => "Commercial Beef - Fore-Quarter", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1082", 'description' => "Commercial Beef - Hind-Quarter", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1083", 'description' => "Commercial Beef - Sides", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1086", 'description' => "CM-COM Grade - ForeQuarter", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1087", 'description' => "CM-COM Grade - HindQuarter", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1091", 'description' => "CMFAQ Grade - ForeQuarter", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1092", 'description' => "CMFAQ Grade - HindQuarter", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1096", 'description' => "CMSTD Grade - ForeQuarter", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1097", 'description' => "CMSTD Grade - HindQuarter", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1100", 'description' => "Lamb- Species", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1101", 'description' => "Lamb- Livestock", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1119", 'description' => "Leg for Salami", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1153", 'description' => "Imp Xxxx Xxxxx[Xpt Mkt] - WIP", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1157", 'description' => "Imp Shoulder B'ss R'ss [Xpt]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1200", 'description' => "Goat- Species", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1201", 'description' => "Goat- Livestock", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1202", 'description' => "Goat Carcass", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1227", 'description' => "Goat Blood Meat", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1229", 'description' => "Chevon", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1253", 'description' => "Bone/Meat Dust", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1315", 'description' => "Commercial Beef Fillet Head", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1321", 'description' => "Blood Plasma", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1400", 'description' => "High Grade Beef Carcass", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1401", 'description' => "Commercial Beef Carcass", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1402", 'description' => "High Grade - Fore-Quarters", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1403", 'description' => "High Grade - Hind-Quarters", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1404", 'description' => "Commercial Beef - Fore-Quarter", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1405", 'description' => "Commercial Beef - Hind-Quarter", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1406", 'description' => "High Grade - F/Q less B'I Beef", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1431", 'description' => "Neck B'In Beef", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1432", 'description' => "Neck Boneless Beef", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1433", 'description' => "Whole Sirloin On Rump", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1437", 'description' => "Neck B'In Cube", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1438", 'description' => "Beef Stewing Steak", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1439", 'description' => "Beef Baron", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1440", 'description' => "Topside (U) [Sale]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1440A", 'description' => "Topside Portion [U]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1442", 'description' => "Silverside/EyePiece (Bf Bacon)", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1443", 'description' => "Topside- Pressed Beef/Marinate", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1444", 'description' => "Topside for Pastrami", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1445", 'description' => "Topside- Rolled Beef [U]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1446", 'description' => "Eye Piece (for Smoked Beef)", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1447", 'description' => "Silverside (Beef Bacon/Sale)", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1447A", 'description' => "Silverside Portion [U]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1448", 'description' => "Silverside strips for Biltong", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1449", 'description' => "Rump Steak High Grade [U]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1449A", 'description' => "Rump Steak Portion [U]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1450", 'description' => "Rump Steak- Rolled Beef [U]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1451", 'description' => "Rump Steak- Slices [U]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1452", 'description' => "Striploin", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1452A", 'description' => "Striploin Portion [U]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1453", 'description' => "Striploin- Rolled Beef [U]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1454", 'description' => "Striploin Steak", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1455", 'description' => "Striploin (for Pastrami)", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1456", 'description' => "Sirloin [U]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1457", 'description' => "Beef T-Bone [M]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1458", 'description' => "Half Rib Eye [M]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1459", 'description' => "Beef Fillet (Purchase)", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1460", 'description' => "B'In Shin", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1461", 'description' => "Beef Fillet Trimmed [U]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1462", 'description' => "Brisket Boneless for Roll", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1463", 'description' => "Meaty Beef Ribs", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1464", 'description' => "Lean Beef", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1465", 'description' => "Beef Bones", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1465S", 'description' => "Beef Soft Bones", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1466", 'description' => "Sudan Beef Cubes", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1467", 'description' => "Pistola- High Grade Beef", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1468", 'description' => "Beef Cubes [M]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1468A", 'description' => "Beef Cubes [M] - (UN Agility)", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1469", 'description' => "Beef- Off-Cuts [U]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1470", 'description' => "Beef Blood Meat", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1471", 'description' => "Beef Fat", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1472", 'description' => "Bone-in Beef", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1473", 'description' => "Ox-tail", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1474", 'description' => "Ox-tail Slices", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1475", 'description' => "Rib Eye Bín [M]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1476", 'description' => "Striploin Strip [M]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1477", 'description' => "Commercial Pistola", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1478", 'description' => "Sliced B'In Beef", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1479", 'description' => "Gristles", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1480", 'description' => "Stamped Beef", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1481", 'description' => "Ox-Kidney", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1483", 'description' => "Prego Steak [U]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1484", 'description' => "B'In Shin- (Osubuko)", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1485", 'description' => "Sliced B'In Cube", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1486", 'description' => "Half Sirloin [U]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1486A", 'description' => "Half Sirloin Portion [U]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1487", 'description' => "Half Striploin [U]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1487A", 'description' => "Half Striploin Portion [U]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1488", 'description' => "Beef Fillet Portions [M]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1489", 'description' => "Beef Pie", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1490", 'description' => "Steak Strips (Beef)", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1491", 'description' => "Topside Slices/Portions [M]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1492", 'description' => "Commercial Rib-Eye B'In", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1492A", 'description' => "Commerci Rib-Eye BI Portion[U]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1493", 'description' => "Thick Flank/Top Rump/StewStk", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1494", 'description' => "Beef Neck Fillet/UpperLoin[U]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1495", 'description' => "Rib Eye- Rolled Beef [M]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1496", 'description' => "Striploin (Trimmed) [M]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1497", 'description' => "Topside (Trimmed 5506) [M]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1498", 'description' => "Rump Steak (Trimmed) [M]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1499", 'description' => "Beef Steak [M]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1500", 'description' => "Beef Escalop/UpperLoin [M]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1501", 'description' => "Beef- Off-Cuts [M]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1502", 'description' => "Commercial ½ Striploin", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1502A", 'description' => "Commerc ½ Striploin Portion[U]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1503", 'description' => "Beef Cubes [U]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1504", 'description' => "Beef Fillet Portions [U]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1505", 'description' => "Sirloin Steak/Rib Eye B'ss [U]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1506", 'description' => "Striploin Strip [U]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1507", 'description' => "Rump Steak- Slices [M]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1508", 'description' => "Beef T-Bone [U]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1509", 'description' => "Beef Neck Fillet- Rolled [M]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1510", 'description' => "Rib Eye- Rolled Beef [U]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1511", 'description' => "Rump Steak- Rolled Beef [M]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1512", 'description' => "Striploin- Rolled Beef [M]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1513", 'description' => "Topside (Trimmed 5512) [M]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1514", 'description' => "Topside- Rolled Beef [M]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1515", 'description' => "Commercial Topside [U]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1515A", 'description' => "Commercial Topside Portion [U]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1516", 'description' => "Commercial Striploin [U]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1516A", 'description' => "Commercia Striploin Portion[U]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1517", 'description' => "Silverside Trimmed [M]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1518", 'description' => "Portioned Rib Eye Steak [M]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1519", 'description' => "Beef Upperloin Cube [M]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1520", 'description' => "Striploin Trims [U]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1521", 'description' => "Prego Steak Portion [M]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1522", 'description' => "Rib Off Beef [M]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1523", 'description' => "T-Bone Trimmed [U]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1524", 'description' => "Lean Beef [M]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1525", 'description' => "TSide- for Beef Bacon/Smk Beef", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1526", 'description' => "Rib Eye Bin Trimmed [M]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1527", 'description' => "Half Striploin Trimmed [M]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1528", 'description' => "Rolled ½Striploin Trimmed [M]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1529", 'description' => "Rolled Beef Brisket [M]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1530", 'description' => "Rump Steak (Trimmed) [U]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1531", 'description' => "Sirloin Trimmed [M]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1532", 'description' => "Rib Eye B'In [U]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1532A", 'description' => "Rib Eye B'In Portion [U]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1533", 'description' => "Topside Slices/Portions [U]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1534", 'description' => "Beef Spare Ribs", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1535", 'description' => "Shin Off Bone 500g", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1536", 'description' => "Beef Fillet Trimmed [M]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1537", 'description' => "Commercial Rump Steak [U]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1537A", 'description' => "Commercia RumpSteak Portion[U]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1538", 'description' => "Commercial Portions [M]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1539", 'description' => "Continental Beef[M]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1540", 'description' => "Rib-eye B'in Portion", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1541", 'description' => "Beef Buttock", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1542", 'description' => "Barbeque Ribs", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1543", 'description' => "Beef B'In Off-Cuts [U] [Sale]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1544", 'description' => "Beef Fillet Head - [X-Sirloin]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1545", 'description' => "Beef Fillet Off silverskin [U]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1546", 'description' => "Brisket Trimmed- [M]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1547", 'description' => "Beef Leg B'In", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1548", 'description' => "Beef Leg Boneless", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1549", 'description' => "Trimmed Sirloin (U)", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1550", 'description' => "Tenderlised Steaks (U)", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1551", 'description' => "Tenderlised R/Steak (M)", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1552", 'description' => "Portion Shin Off Bone", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1553", 'description' => "Beef Hump", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1554", 'description' => "Braising Steaks", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1555", 'description' => "Rump Steak Picanha", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1556", 'description' => "Rump Top [M]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1557", 'description' => "Rib Eye Bin - NAS", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1558", 'description' => "Sopa Braising", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1559", 'description' => "Commercial Eye Piece -Smk Beef", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1560", 'description' => "Commercial SilverSide- BBc/Sal", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1560A", 'description' => "Commerc SilverSide Portion [U]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1561", 'description' => "Commercial Sirloin [U]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1562", 'description' => "Commercial Half Sirloin [U]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1562A", 'description' => "Commerc 1/2Sirloin Portion [U]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1563", 'description' => "Commercial Thck-Flank/Top Rump", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1564", 'description' => "Comm. Bf Neck-Fillet/U-Loin[U]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1565", 'description' => "Commercial Beef Fillet", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1566", 'description' => "Lean Beef Steak [M]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1567", 'description' => "Commercial T-Bone Steak [U]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1568", 'description' => "Bone/Meat Dust", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1569", 'description' => "Lean Meat [Ox-head]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1570", 'description' => "Jaw Meat [Ox-head]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1571", 'description' => "Whole Beef Ribs with Meat", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1572", 'description' => "Boneless Beef Chuck", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1573", 'description' => "Rib Eye Steak Bin - NAS", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1574", 'description' => "Commercial Rib Eye B'In [U]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1575", 'description' => "Beef Stewing Strips", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1576", 'description' => "Beef Brisket Bone In", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1577", 'description' => "Beef Chuck Bone In", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1583", 'description' => "Feather Steak [M]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1584", 'description' => "Staff Meat", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1585", 'description' => "Beef Fillet Head Trimmed", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1587", 'description' => "Succulent Beef Cubes [M]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1588", 'description' => "Commercial Beef Fillet Trim[U]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1589", 'description' => "FAQ Deboned Beef/kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1590", 'description' => "Beef Meaty Soup Bones", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1591", 'description' => "Boneless Beef Meat [All] ", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1592", 'description' => "Beef Middle Cut-Bone In/kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1604", 'description' => "Turkey Meat for Roll/ChckSsg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1612", 'description' => "Turkey Breast", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1614", 'description' => "Turkey Thigh", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1615", 'description' => "Turkey Skin/Trimming/BloodMeat", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1655", 'description' => "Chicken Skin/Trimmings", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1657", 'description' => "Chicken Meat", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1900", 'description' => "Lamb- Carcass", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1901", 'description' => "Lamb Leg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1902", 'description' => "Lamb Middle", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1903", 'description' => "Lamb Shoulder Whole", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1911", 'description' => "Lamb Long Loin", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1912", 'description' => "Lamb Loin Chops", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1913", 'description' => "Lamb Belly Spare Ribs", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1914", 'description' => "Rack of Lamb", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1915", 'description' => "Lamb Short Loin", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1916", 'description' => "Lamb Shoulder from Long Loin", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1917", 'description' => "Lamb Arm", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1921", 'description' => "Lamb Shoulder B'In", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1922", 'description' => "Lamb Shoulder Ribs", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1923", 'description' => "Lamb Shld Shanks", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1924", 'description' => "Lamb Blood Meat", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1925", 'description' => "Lamb Shoulder Chops", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1926", 'description' => "Lamb Stamps", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1927", 'description' => "Lamb Neck", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1928", 'description' => "Sliced Lamb Shld Shanks", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1929", 'description' => "Sliced Lamb Arm Cubes", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1930", 'description' => "Lamb Neck Fillet for T-bn chop", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1931", 'description' => "Lamb Leg B'ss", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1932", 'description' => "Lamb Fat", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1933", 'description' => "Mutton", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1934", 'description' => "Lamb Bones", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1935", 'description' => "Lamb Kidney", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1936", 'description' => "Lamb Off-Cuts", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1937", 'description' => "Lamb Leg B'In", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1938", 'description' => "Reformed Lamb Leg Meat", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1951", 'description' => "Rolled B'less Lamb Leg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1961", 'description' => "Lamb Cubes", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1962", 'description' => "Sliced Lamb Neck", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1963", 'description' => "Lamb T-Bone Chops", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1964", 'description' => "Lamb Leg Shanks", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1965", 'description' => "Lamb Rib Cube BÍn", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1966", 'description' => "Lamb Shoulder BIn Cube", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1967", 'description' => "Lamb Leg Steak", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1968", 'description' => "Lamb Shoulder- Ribs & Shanks", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1969", 'description' => "Sliced Lamb Spare Ribs", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1970", 'description' => "Hand of Lamb", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1971", 'description' => "Lamb Baron", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1972", 'description' => "Lamb Leg Off shanks", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1973", 'description' => "Saddle of Lamb", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1974", 'description' => "Lamb Leg Sliced", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1975", 'description' => "Lamb Loin Boneless", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1976", 'description' => "Lamb Eye Muscle", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1977", 'description' => "Lamb Loin Off Eye Muscle", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1978", 'description' => "Lamb Loin Off Muscle Bin cube", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1979", 'description' => "Lamb Cutlet", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1980", 'description' => "Reformed Lamb Shoulder Meat", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG1981", 'description' => "Lamb Leg Chump Off", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG5051", 'description' => "Green Lean Bf [M]- [Canning]", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG5501", 'description' => "Marinated HG Rump Steak", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG5502", 'description' => "Marinated Striploin", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG5503", 'description' => "Marinated Sirloin", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG5504", 'description' => "Marinated Bf Fillet Trim- Bulk", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG5505", 'description' => "Marinated ThickFlank/Stw Steak", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG5506", 'description' => "Marinated Topside - 1443", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG5507", 'description' => "Marinated Silverside", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG5508", 'description' => "Marinated Half Sirloin", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG5509", 'description' => "Marinated Half Striploin", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG5510", 'description' => "Marinated Beef Brisket", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG5511", 'description' => "Marinated Beef Upperloin", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG5512", 'description' => "Marinated Topside - 1440", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG5513", 'description' => "Marinated Commercial Topside", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG5514", 'description' => "Marinated Commercial Striploin", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG5515", 'description' => "Marinated T-Bone Trimmed", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG5516", 'description' => "Marinated Eye Piece", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG5517", 'description' => "Marinated Rib Eye B'In", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG5518", 'description' => "Marinated Striploin Trimmed", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG5519", 'description' => "Marinated Comm Rump Steak", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG5520", 'description' => "Marinated Bone-In Beef", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG5521", 'description' => "Marinated Meaty Beef Ribs", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG5522", 'description' => "Marinated Braising Steak", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG5523", 'description' => "Marinated Comm T-Bone Steak", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG5524", 'description' => "Marinated Comm. Beef Fillet", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG5531", 'description' => "Marinated Beef Neck B'ss", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG5701", 'description' => "Marinated Lamb Long Loin", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG5702", 'description' => "Marinated Lamb Reformed Leg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG5801", 'description' => "Matured HG Rump Steak", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG5802", 'description' => "Matured Striploin", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG5803", 'description' => "Matured Whole Sirloin on Rump", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BG6003", 'description' => "Celestine", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31010301", 'description' => "Meaty Meaty Sausages 400gms", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31010302", 'description' => "Meaty Meat Sausages 1kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31010303", 'description' => "Meaty Meat Sausages 4kgs", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31010502", 'description' => "Value Pack Meat Sausages 1kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31010803", 'description' => "Smoked Mini Bites 250gms", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31010804", 'description' => "Smoked Mini Bites 500gms", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31010805", 'description' => "Smoked Mini Bites 1kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31011401", 'description' => "Turkey Stuffing 400gms", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31011402", 'description' => "Turkey Stuffing 3kgs", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31011403", 'description' => "Turkey Stuffing 1kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31015101", 'description' => "Beef Chipolatas 200gms", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31015102", 'description' => "Beef Chipolatas 1kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31015104", 'description' => "Beef Chipolatas 1kg - SER", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31015201", 'description' => "Meaty Beef Sausages - 500gms", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31015202", 'description' => "Meaty Beef Sausages 1kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31015206", 'description' => "NAS Beef Sausages 960gm", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31015207", 'description' => "Meaty Beef Sausages 1kg - SER", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31015210", 'description' => "Mombasa Beef Sausages - 250gms", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31015301", 'description' => "Spicy Beef Sausages 500gms", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31015302", 'description' => "Spicy Beef Sausage Meat 3kgs", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31015303", 'description' => "Spicy Beef Sausage Meat 1kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31015304", 'description' => "Spicy Beef Sausages 4kgs", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31015305", 'description' => "Spicy Beef Sausages 1kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31015306", 'description' => "Spicy Beef Sausage 1kg Ex long", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31015308", 'description' => "Spicy Beef Chipolatas", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31015310", 'description' => "Spicy Beef Sausages V/P 1kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31015401", 'description' => "Value Pack Beef Sausages 1kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31015402", 'description' => "Beef Sausage Meat 3kgs", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31015403", 'description' => "Beef Sausage Meat 400gms", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31015404", 'description' => "Beef Sausage Meat 1kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31015405", 'description' => "Beef Biltong Bulk", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31015501", 'description' => "Beef Sausages Catering 1kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31015506", 'description' => "Aga Khan Sausages - 1kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31015508", 'description' => "Ponders Beef Catering Sausages 1kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31015601", 'description' => "Use Code BJ31015201", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31015604", 'description' => "Beef Sausages (Sose Token) 250gms", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31015701", 'description' => "Jumbo Sausage 1kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31015801", 'description' => "Boerewors - Beef 500gms", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31015803", 'description' => "Use BJ31015811", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31015805", 'description' => "Choma Sausage 1kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31015806", 'description' => "Boerewors Beef Meat 3kgs", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31015808", 'description' => " Beef Choma Sausage 300gms", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31015810", 'description' => "Meaty Cocktails - 400 gms", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31015904", 'description' => "Low Fat Beef Sausage - 400 gms", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31019102", 'description' => "Chicken Sausages 400gms", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31019106", 'description' => "Blocked", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31019110", 'description' => "Spicy Chicken Value Pack 1kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31021201", 'description' => "Debonnairs", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31021203", 'description' => "Debonnairs Rolled Bacon 200gms", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31021301", 'description' => "Beef Bacon 400gms", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31021302", 'description' => "Beef Bacon 1kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31021303", 'description' => "Beef Bacon 100gms", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31021304", 'description' => "Beef Bacon 200gms", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31021305", 'description' => "Beef Macon 1kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31030351", 'description' => "Beef Continental Salami 200gms", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31030651", 'description' => "Beef Garlic Salami 200gms", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31030802", 'description' => "Italian Meat Dry Salami 1-1.5k", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31030803", 'description' => "Italian Beef Salami Sliced-1kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31030804", 'description' => "Italian Beef Salami 100gm", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31030809", 'description' => "Italian Beef Salami 1-1.5kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31030941", 'description' => "Beef Polony 200gms", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31031201", 'description' => "Poultry Viennas - 300gms", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31031202", 'description' => "Poultry Vienna 500gms", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31031205", 'description' => "Poultry Viennas 250gms", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31031401", 'description' => "Black Pudding- Bulk 1-1.5kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31031403", 'description' => "Black Pudding 125gms", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31031502", 'description' => "Beef Brawn- Sliced - 200gms", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31031503", 'description' => "Beef Brawn - Sliced 500gms", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31031504", 'description' => "Beef Brawn - Sliced 1kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31031505", 'description' => "Beef Brawn 3 -3.5 kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31031702", 'description' => "Beef Smokies Labless 1Kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31031704", 'description' => "Beef Smokies Extra Long 1kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31031706", 'description' => "Beef Smokies Ex-long 400gm", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31031710", 'description' => "Retail Beef Smokies 900gms", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31031712", 'description' => "Jet Sausage - 1 Kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31031802", 'description' => "Beef Vienna - 500gms", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31031803", 'description' => "Beef Viennas - 500gms Ex-long)", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31031806", 'description' => "Beef Viennas 1kg (Extra Long)", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31031807", 'description' => "Beef Vienna Chipolata /kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31031809", 'description' => "Beef Viennas 1kg - Bonus", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31031813", 'description' => "Beef Viennas 250gms", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31031815", 'description' => "Beef Vienna - 500gms - SER", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31040101", 'description' => "Beef Pastrami-Bulk (1.5-2.3kg)", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31040102", 'description' => "Beef Pastrami 100gms", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31040103", 'description' => "Sliced Beef Pastrami 1kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31040801", 'description' => "Pepperoni sliced - 1kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31040901", 'description' => "Servelat, 200gms", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31040903", 'description' => "Servelat, 1kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31040904", 'description' => "Servelat Ex-long /kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31041300", 'description' => "Cooked Meat Balls, 1 Kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31050101", 'description' => "Black Forest Ham(prosc) 100gms", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31050102", 'description' => "Black Forest Ham(prosc)0.7-1kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31051250", 'description' => "Deli Roast Beef per kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31051301", 'description' => "Smoked Beef, 200gms", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31051302", 'description' => "Smoked Beef, Bulk", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31051401", 'description' => "Smoked Beef - Sliced 1kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31065101", 'description' => "Sandwich Beef, 200gms", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31065102", 'description' => "Sandwich Beef 500gms", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31065103", 'description' => "Sandwich Beef Bulk, per kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31065201", 'description' => "Sliced Sandwich Beef, 1kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31065301", 'description' => "Chopped Sandwich Beef Bulk", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31080201", 'description' => "Beefo Pet Food, 1x2 kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31090220", 'description' => "Striploin Steaks 500gm", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31090229", 'description' => "Blood Meat Per Litre", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100100", 'description' => "Export Beef Fillet/ Kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100101", 'description' => "Beef Bone-In", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100102", 'description' => "Beef Cubes, 500 gms", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100103", 'description' => "Beef Fillet/Kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100104", 'description' => "Beef Ribs Bones Per Kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100105", 'description' => "Beef Rump Steak 500gms", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100106", 'description' => "Beef Sirloin, Per Kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100107", 'description' => "Beef Striploin, Per Kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100108", 'description' => "Use Code BJ31100325", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100109", 'description' => "Boneless Beef", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100110", 'description' => "Brisket (Rolled Beef) Per Kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100111", 'description' => "Beef Cubes Topside", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100114", 'description' => "Lean Beef", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100115", 'description' => "High Grade Pistola, Per Kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100116", 'description' => "Minced Beef (High Grade), Kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100117", 'description' => "Minced Beef 2 Kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100118", 'description' => "Osubuko (Shin on Bone)", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100119", 'description' => "Ox-Kidney", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100121", 'description' => "Ox-Tail per kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100122", 'description' => "Prego Steak", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100123", 'description' => "Rib Eye Steak, Per Kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100124", 'description' => "Rump Steak, Per Kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100125", 'description' => "Silverside, Per Kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100126", 'description' => "Soup Bones (Beef)", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100127", 'description' => "Staff Meat, Per Kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100128", 'description' => "Steak Strips (Beef)", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100129", 'description' => "T-Bone Steak, Per Kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100130", 'description' => "Beef Topside, Per Kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100131", 'description' => "Minced Beef 500g (High Grade)", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100132", 'description' => "Beef Upper Loin per Kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100133", 'description' => "B/Rolled T/side Joint B/less/k", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100134", 'description' => "Export Beef Goulash", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100135", 'description' => "Rib Eye Steak B'In Frenched", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100136", 'description' => "Beef Fillet, Per Kg - SER", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100137", 'description' => "Beef Striploin, Per Kg - SER", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100138", 'description' => "Rump Steak, Per Kg - SER", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100139", 'description' => "Topside, Per Kg - SER", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100140", 'description' => "Beef Sirloin w Fillet Attached", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100141", 'description' => "fr-Beef Burger(4x200gms)-Bonus", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100143", 'description' => "Fresh Beef Burgers 5x140gms", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100144", 'description' => "Fresh Beef Burgers, 200gms", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100145", 'description' => "Fresh Beef Burger (4x200gms)", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100146", 'description' => "Fresh Beef Burgers, 1kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100147", 'description' => "Fresh Beef Burger (10x80gms)", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100148", 'description' => "Gristles", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100152", 'description' => "Fresh Patty Burger 1kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100154", 'description' => "Beef T-Bone 500gm", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100156", 'description' => "Short Cut  Striploin /kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100157", 'description' => "Frozen T-Bone Steak 300gm", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100158", 'description' => "Frozen Striploin Steak 300gm", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100159", 'description' => "Frozen Rump Steak 300gm", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100160", 'description' => "Frozen Beef Fillet Steak 300gm", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100161", 'description' => "Frozen Rib Eye Steak 300gm", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100162", 'description' => "Frozen Stir-Fry B/f Strips300g", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100163", 'description' => "Frozen Beef Rump Steak 250gms", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100164", 'description' => "Beef Fillet Portioned 60gm Stk", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100165", 'description' => "Beef Pie Meat Per kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100166", 'description' => "Eight Bone Rib Sirloin", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100167", 'description' => "Meaty Beef Ribs /kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100168", 'description' => "Portioned T-bone Steak", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100169", 'description' => "Portioned Rump Steak /Kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100170", 'description' => "Portioned Beef Fillet Per kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100171", 'description' => "Portioned Sirloin Steak /Kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100172", 'description' => "Portioned Rib Eye Steak", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100173", 'description' => "Com. Beef Pistola", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100175", 'description' => "Beef Fillet Medallions (100gm)", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100176", 'description' => "Rib of Beef (7-8 bone)", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100177", 'description' => "Shin Meat (Off the Bone)", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100178", 'description' => "Smoked Beef Ribs per kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100180", 'description' => "Fresh Beef Burger 1kg - Bonus", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100181", 'description' => "Minced beef 1kg- Bonus", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100182", 'description' => "Minced beef 2kg- Bonus", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100183", 'description' => "Rib Eye Beef (Rolled) per kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100184", 'description' => "Beef Offcuts", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100185", 'description' => "Tenderized Rump Steak 100gms", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100186", 'description' => "Beef Thick Flank", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100187", 'description' => "Whole Beef Rib with Meat", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100188", 'description' => "Frozen Beef Mince 500gm", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100189", 'description' => "Rolled Rump Steak", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100190", 'description' => "Rolled Striploin", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100191", 'description' => "Beef Steak Per kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100193", 'description' => "Portioned Beef Striploin /kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100195", 'description' => "Serena Steaks", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100196", 'description' => "Frozen Beef Cubes 500gms", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100197", 'description' => "Frozen Beef Mince 500gm Promo", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100198", 'description' => "Beef Steaks 250gms", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100199", 'description' => "Beef Steaks - 500gms", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100200", 'description' => "Beef Spare Ribs Per Kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100201", 'description' => "Tenderized Beef Steaks-150 gms", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100202", 'description' => "Fresh Beef Burger 200gms Promo", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100203", 'description' => "Rib Eye End - Bone in", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100204", 'description' => "Beef Buttock per kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100205", 'description' => "Beef Topside Cubed", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100206", 'description' => "Beef Swarma", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100207", 'description' => "Barbecue Beef Ribs per kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100208", 'description' => "Prego Steaks,150gms", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100209", 'description' => "Fresh Beef Burger Meat - 1 Kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100210", 'description' => "Portioned Topside Per kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100211", 'description' => "Whole Rib Eye B'less", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100212", 'description' => "Whole Rib Eye B'in", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100213", 'description' => "Fresh Beef Burger 400gms", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100214", 'description' => "Beef Leg Bone-In", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100215", 'description' => "Beef Leg Boneless", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100216", 'description' => "Retail Rib Eye Steak Per Kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100217", 'description' => "Retail Rumpsteak Per Kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100218", 'description' => "Retail Topside Per Kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100219", 'description' => "Use BJ31100307", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100220", 'description' => "Beef Hump per kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100221", 'description' => "Single Beef Ribs Per kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100222", 'description' => "Beef Braising Steak Per kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100223", 'description' => "Top Rump", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100224", 'description' => "Rib Eye Stk Bone-In Portioned", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100225", 'description' => "HG Beef Carcass whole, per Kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100226", 'description' => "Baron Of Beef", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100227", 'description' => "Diced Beef, Per Kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100228", 'description' => "Economy Minced Beef, 500 gms", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100229", 'description' => "Frozen Econ Minced Beef 500gms", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100230", 'description' => "Chilled Beef Mince, 500gms Exp", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100231", 'description' => "Matured Beef Fillet/Kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100232", 'description' => "Matured Rump Steak/Kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100233", 'description' => "Matured Rib Eye Steak/Kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100234", 'description' => "Matured Beef Striploin/Kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100235", 'description' => "Matured T-Bone Steak/Kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100236", 'description' => "Boneless Beef Chuck per kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100237", 'description' => "Com Beef Carcass FQrt, per Kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100238", 'description' => "Com Beef Carcass Side, per Kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100239", 'description' => "Com Beef Carcass whole, per Kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100240", 'description' => "HG Beef Carcass Side, per Kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100244", 'description' => "Cubed Stewing Beef /Kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100248", 'description' => "Bulk Brisket per kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100250", 'description' => "Sirloin Whole Bones", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100266", 'description' => "Beef Bones", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100267", 'description' => "Gall Stones", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100268", 'description' => "Stewing Beef Strips/Kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100269", 'description' => "Meaty Soup Bones,2kgs", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100270", 'description' => "Beef Marrow Bones /kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100271", 'description' => "Beef Striploin Sliced, Per Kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100272", 'description' => "CM Bone Dust/kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100273", 'description' => "Fillet Head (Beef)/ Kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100274", 'description' => "Beef Chuck Bone-in/kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100275", 'description' => "Cattle Bile Juice per can", 'unit_of_measure' => "LTR", 'category' => "cm-prod"], 
            ['code' => "BJ31100276", 'description' => "Beef Skirt Steak/kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100277", 'description' => "Cattle Eyes", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100278", 'description' => "CMSTD Beef Forequarter/kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100279", 'description' => "CMSTD Beef Hindquarter/kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100280", 'description' => "CMFAQ Beef Forequarter/kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100281", 'description' => "CMFAQ Beef Hindquarter/kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100287", 'description' => "Vacuum Packed  Beef Fillet 500g", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100291", 'description' => "Beef Soft Bones", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100292", 'description' => "Ox Lung Wholesale/kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100295", 'description' => "UN Beef Stewing Boneless/Kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100301", 'description' => "Fresh Beef Picanha", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100302", 'description' => "Chilled Striploin Steak, 300gm", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100303", 'description' => "Chilled Rump Steak, 300 gms", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100305", 'description' => "Succulent Beef Steaks, 12x150g", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100306", 'description' => "Beef Sirloin Steak, 500gms", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100307", 'description' => "Retail Beef Fillet, 500gms", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100313", 'description' => "HG Beef Carcass Without Kidney", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100315", 'description' => "Beef Cheek Meat/kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100318", 'description' => "Feather Steaks per kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100320", 'description' => "Beef Brisket B'ss Cubed/kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100321", 'description' => "Beef Neck B'ss Cubed/kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100325", 'description' => "Cubed Beef on the Bone /kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100326", 'description' => "Succulent Beef Cubes Per Kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100327", 'description' => "Beef Brisket Bone-in/kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100350", 'description' => "Chilled Matumbo/kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100351", 'description' => "Classic Beef Cubes/kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100352", 'description' => "Classic Beef Strips/kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100353", 'description' => "Standard Grade Beef Carcass/kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100354", 'description' => "FAQ Grade Beef Carcass/kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100355", 'description' => "HG Whole Deboned Carcass/kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100356", 'description' => "Meat on Bone - Beef /kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100357", 'description' => "Cubed Meat on Bone - Beef /kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100358", 'description' => "Sliced Shin On Bone/ Kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100364", 'description' => "Feedlot Portioned Striploin/kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100365", 'description' => "Feedlot Portioned RumpSteak/kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100367", 'description' => "Feedlot Beef Striploin/kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100368", 'description' => "Feedlot Beef RumpSteak/kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100369", 'description' => "Beef Middle Cut-Bone In/kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100370", 'description' => "Beef Tender Steak/ Kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100371", 'description' => "Beef SKulls/kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100372", 'description' => "Minute Beef Steaks/ Kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100373", 'description' => "Prime Marbled Striploin/Kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100375", 'description' => "Beef Casserole/Kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100390", 'description' => "Savoury Meat Balls, 300 gms", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100391", 'description' => "Meat Balls, 1 Kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100392", 'description' => "Meat Balls, 500 gms", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100401", 'description' => "Java Fresh Beef Burgers (6 x160gms)", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100402", 'description' => "Java Kiddie Burger 10x80gms", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100403", 'description' => "Java  Burger 8Kg, Bulk", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100408", 'description' => "Kiddie Beef Burgers 200gm", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100409", 'description' => "Innscor Beef Burgers, 100gms", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100410", 'description' => "Chicken Inn Burger 100gms", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100411", 'description' => "Chicken Inn Burger 80gm", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100415", 'description' => "Fresh Beef Burger (10x80gms)", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100418", 'description' => "Ennsvalley Burgers, 1kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100420", 'description' => "Fresh Boerewor Beef Burger200g", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100421", 'description' => "Fresh Boerewor Beef Burger400g", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100422", 'description' => "Fresh Boerewor Beef Burger 1kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100501", 'description' => "Wimpy Burger 1kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31100502", 'description' => "Wimpy Burger (10 x 80 gms)", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31120110", 'description' => "Chicken Burger 200gm", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31120111", 'description' => "Chicken Burger 1 kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31120112", 'description' => "Chicken Burger 200g-pro", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31120113", 'description' => "Chicken Burger Meat Per Piece", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31120114", 'description' => "Chicken Burger 1kg (special)", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31120115", 'description' => "Chicken Burger 400gms", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31120116", 'description' => "Chicken Burger (10x80gms)", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31120121", 'description' => "Dorman's Fresh Burger 10x120g", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31120152", 'description' => "Innscor Beef Burgers, 1 kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31120160", 'description' => "Minced Beef Square Café/kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31121001", 'description' => "Whole Lamb 14-18kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31121002", 'description' => "Lamb Leg /kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31121003", 'description' => "Lamb Leg B'less 2.2kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31121004", 'description' => "Mutton", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31121005", 'description' => "Lamb Shoulder Bone-In/kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31121006", 'description' => "Cubed Bone-in Lamb /kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31121007", 'description' => "Cubed B'less Lamb (Diced) /kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31121008", 'description' => "Lamb Loin, Bone In /kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31121009", 'description' => "Lamb Shoulder Shanks /kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31121010", 'description' => "Lamb Off Cuts /kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31121011", 'description' => "Lamb Ribs /kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31121012", 'description' => "Lamb Loin Chops /kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31121013", 'description' => "Lamb Shoulder Chops /kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31121014", 'description' => "Rack of Lamb (12-14pcs) Per kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31121015", 'description' => "Lamb Loin Chops 500gm", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31121016", 'description' => "Lamb Shoulder Chops 500gm", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31121017", 'description' => "Frenched Rack of Lamb/kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31121018", 'description' => "Lamb Casserole", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31121019", 'description' => "Lamb Hocks", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31121020", 'description' => "Lamb Leg Shanks Per kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31121021", 'description' => "Sliced Lamb Leg Steak /kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31121022", 'description' => "Hand of Lamb per kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31121023", 'description' => "Roast Leg of Lamb per kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31121024", 'description' => "Lamb Leg Steak w/out Shank /kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31121025", 'description' => "Baron Of Lamb", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31121026", 'description' => "Saddle Of Lamb", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31121027", 'description' => "Sliced Lamb Leg per kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31121029", 'description' => "Lamb Kidney, Per Kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31121030", 'description' => "Lamb Loin Boneless, Per kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31121031", 'description' => "Lamb Mince, Per Kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31121032", 'description' => "Lamb Loin Fillet /kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31121033", 'description' => "Lamb Loin Eye per kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31121034", 'description' => "Lamb Leg /kg - SER", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31121035", 'description' => "Lamb Barnsly Chops", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31121036", 'description' => "Lamb Cutlets", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31121039", 'description' => "Lamb Fat/kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31121045", 'description' => "Lamb Meaty Ribs /kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31121049", 'description' => "Lamb Arm /kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31121056", 'description' => "Lamb T-Bone Chops /kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31121060", 'description' => "Lamb Leg Chump Off/kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31121064", 'description' => "Lamb Bones/kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31150101", 'description' => "Whole Goat /kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31150105", 'description' => "Goat Liver/kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31150106", 'description' => "Goat Kidney/kg", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BJ31150111", 'description' => "Goat Hide / Skin", 'unit_of_measure' => "KG", 'category' => "cm-prod"], 
            ['code' => "BK35010605", 'description' => "Doinyo C-bell Cream(T)24x200ml", 'unit_of_measure' => "LTR", 'category' => "cm-prod"], 


        );        

        foreach ($items as $item) {
            $code = $item['code'];
            $description = $item['description'];
            $category = $item['category'];

            if (array_key_exists('unit_of_measure', $item)) {
                $unit_of_measure = $item['unit_of_measure'];
            } else {
                $unit_of_measure = null;
            }
            
            Item::firstOrCreate(
                [
                    'code' => $code,
                    
                ],
                [
                    'description' => $description,
                    'unit_of_measure' => $unit_of_measure,
                    'category' => $category
                ]
            );
        }
    }
}
